name: golangci-lint

#on: [push, pull_request]
on:
  push:
    #    branches: [ master ]
    branches:
#      - '*'         # Matches zero or more characters, but does not match the / character. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
#      - '*/*'       # Matches every branch containing a single '/'
      - '**'        # Matches zero or more of any character.
#      - '!master'   # Excludes master
  pull_request:
    #    branches: [ master ]
    branches:
      - '**'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18' , '1.19'  , '1.20' , '1.21' , '1.22']
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
