name: golangci-lint

#on: [push, pull_request]
on:
  push:
    #    branches: [ master ]
    branches:
      - '*'
  pull_request:
    #    branches: [ master ]
    branches:
      - '*'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.16', '1.17', '1.18' , '1.19'  , '1.20' ]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
